uploads = []
generated = []

[[outputs]]
id = "trcvOnwQRvXreAzVJbGUK"
uri = "file://artifacts/highlighter-extension/highlighter-extension.zip"
type = "unspecified"
title = "Highlighter Extension v0.1.4 (folder fixes)"
