uploads = []
generated = []

[[outputs]]
id = "trcvOnwQRvXreAzVJbGUK"
uri = "file://artifacts/highlighter-extension/highlighter-extension.zip"
type = "unspecified"
title = "Highlighter Extension v0.2.0 (color match via background message)"
